/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "gpio.h"

int main(void)
{
    uint8_t lastSwitchState = 0;
    uint8_t currentSwitchState;

    GPIO_Init();

    while (1)
    {
        currentSwitchState = Read_Switch();


        if ((currentSwitchState == 1) && (lastSwitchState == 0))
        {
            Delay_ms(20);

            if (Read_Switch() == 1)
            {
                LED_Toggle();
            }
        }

        lastSwitchState = currentSwitchState;
    }
}
