/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "gpio.h"

int main(void)
{
    uint8_t switchState = 0;
    uint8_t lastSwitchState = 0;
    uint8_t pressCount = 0;

    GPIO_Init();

    while (1)
    {
        switchState = Read_Switch();


        if ((switchState == 1) && (lastSwitchState == 0))
        {
            Delay_ms(20);

            if (Read_Switch() == 1)
            {
                pressCount++;

                if (pressCount == 1)
                {
                    Green_LED_On();
                }
                else if (pressCount == 2)
                {
                    Blue_LED_On();
                }
                else if (pressCount == 3)
                {
                    LEDs_Off();
                    pressCount = 0;                   }
            }
        }

        lastSwitchState = switchState;
    }
}






