/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    int num1 = 10;
    int num2 = 20;
    int sum;

    sum = num1 + num2;

    printf("Addition Program on STM32\n");
    printf("Number 1 = %d\n", num1);
    printf("Number 2 = %d\n", num2);
    printf("Sum = %d\n", sum);

    while (1)
    {
        // Infinite loop
    }
}


