/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "my_led.h"
#include "ext_intr.h"

/*
 * Software flag set by ISR
 * volatile because it is shared with ISR
 */
volatile uint8_t exti_event_flag = 0;

/*
 * LED state variable
 * 0 → LED OFF
 * 1 → LED ON
 */
volatile uint8_t led_state = 0;

int main(void)
{
    led_init();        // Initialize LED
    extint_init();     // Initialize EXTI

    while (1)
    {
        /*
         * Check if EXTI interrupt occurred
         */
        if (exti_event_flag)
        {
            /* Toggle software state */
            led_state ^= 1;

            /* Apply state to LED */
            if (led_state)
                led_on(14);
            else
                led_off(14);

            /* Clear event flag */
            exti_event_flag = 0;
        }

        /* Other background tasks can run here */
    }
}
